# This file is referenced by the build.xml file.

name=skteditor
osx.app.name=SKTEditor
rev=1.3.11
client-class=gsfc.spdf.edit.guis.SKTEditor
#client-class=gsfc.spdf.istp.tools.GetNotes
#client-class=gsfc.spdf.istp.tools.CdasMetadata
#client-class=gsfc.spdf.istp.tools.CDFCheck
#client-class=gsfc.spdf.istp.tools.GetAttributes
#client-class=gsfc.spdf.istp.Filename
#
# deploy.url can be eliminated when support for Java 1.6 is dropped
#
# codebase may no longer be needed -- OWS might still need it (or at least
#   deploy.url)
codebase=spdf.gsfc.nasa.gov
#codebase=spdf-dev.sci.gsfc.nasa.gov
#codebase=sscweb.gsfc.nasa.gov
#codebase=sscweb-dev.sci.gsfc.nasa.gov
#deploy.url=
deploy.url=https://${codebase}/skteditor
#deploy.url=https://${codebase}/skteditor/beta
#deploy.url=https://${codebase}/~bharris/skteditor
#
cdf.checksum.value=MD5
notes.file=Notes


test.files=
#test.files=/home/btharris/simple_epoch_made_on_tara.cdf
#test.files=po_h0_tim_00000000_v01-small.cdf
#test.files=~/imap_glows_l1a_hist_20110920_v002.cdf
#test.files=ge_h1_epi_20051121_v03.cdf
#test.files=ac_h0_mfi_20150103_v06.cdf
#test.files=ac_h0_mfi_20150103_v06.cdf isee2_60sec_mfi_19870923_v01.cdf
#test.files=/bigdisk/candey/temp/minxss1_solarSXR_level1_2016-05-16-mission_v5.0.0test.ncdf.cdf
# new Filename test files
#test.files=/home/hleckner/makecdf/psp/L2_ISOIS_032021/masters/psp_isois-epilo_l2-ic_00000000_v01.cdf
#test.files=/home/rcandey/temp/C4_CP_PEA_MOMENTS__20180908_000000_20180909_000000_V200710.37.istp.cdf
#test.files=/home/tkovalic/cdaweb/mms/feeps/FromDave-10-29-2020/mms1_feeps_srvy_l1b_electron_20171002000000_v7.1.1.cdf
#test.files=/home/hleckner/makecdf/formosat_isual/formosat2_k0_isual_20041014110433449_v04.cdf
#test.files=/home/hleckner/makecdf/mms/test_feeps/mms1_feeps_brst_l1b_electron_20171111020513_v7.1.1.cdf
#test.files=/home/cdaweb/data/maven/insitu/kp-4sec/cdfs/2019/02/mvn_insitu_kp-4sec_20190214_v01_r01.cdf /home/cdaweb/data/erg/hep/l2/omniflux/2018/erg_hep_l2_omniflux_20180630_v01_02.cdf /home/cdaweb/data/ibex/h3/release10/ena_hi_nocg_sp_omni_6mo/ibex_h3_ena_hi_r10_nocg_sp_omni_6mo_20150624_map14_v01.cdf
#test.files=erg_mgf_l2_8sec_00000000_v01.cdf erg_mgf_l2_8sec_20170313_v01.01.cdf
#test.files=/home/cdaweb/data/0MASTERS/erg_mgf_l2_8sec_00000000_v01.cdf /home/cdaweb/data/erg/mgf/l2/8sec/2017/erg_mgf_l2_8sec_20170313_v01.01.cdf
#test.files=/home/cdaweb/data/maven/insitu/kp-4sec/cdfs/2019/05/mvn_insitu_kp-4sec_20190514_v15_r02.cdf /home/cdaweb/data/0MASTERS/mvn_insitu_kp-4sec_00000000_v01.cdf /home/cdaweb/data/maven/swea/l2/svypad/2019/05/mvn_swe_l2_svypad_20190514_v04_r03.cdf /home/cdaweb/data/0MASTERS/mvn_swe_l2_svypad_00000000_v01.cdf isee2_60sec_mfi_19870923_v01.cdf
#test.files=/home/cdaweb/data/solar-orbiter/mag/low_latency/ll02/2020/solo_ll02_mag_20201007t000034-20201008t000033_v01i.cdf
# to test GetNotes with multiple DOIs
#test.files=/home/cdaweb/data/0MASTERS/mgs_mag_high_00000000_v01.cdf
# The following isee2 file contains a DOI and VARIABLE_PURPOSE for testing 
# GetNotes.
#test.files=isee2_60sec_mfi_19870923_v01.cdf
# The following mms file contains a DOI
#test.files=/home/cdaweb/data/mms/mms1/edp/brst/l2/scpot/2024/08/mms1_edp_brst_l2_scpot_20240830070513_v2.9.0.cdf
#test.files=ac_h0_mfi_00000000_v01.cdf ac_h0_mfi_20200101_v07.cdf
# utf-8 example
#test.files=/home/mhliu/ac_h1_mfi_20210101_v99.cdf
#test.files=twins_m2_ena_iontemp20100412_v02.cdf
#test.files=/home/btharris/tmp/fast_hr_dcb_00000000000000_v01.cdf
#test.files=cdfTests/IstpVarAttr.cdf
#test.files=/home/cdaweb/data/maven/static/l2/hkp/2014/10/mvn_sta_l2_2a-hkp_20141013_v02_r00.cdf
#test.files=/home/cdaweb/data/0MASTERS/psp_fld_l2_dfb_ac_bpf_dv34hg_00000000_v01.cdf /data/zdata_1/spdf_archive/public/pub/data/psp/fields/l2/dfb_ac_bpf/dv34hg/2019/psp_fld_l2_dfb_ac_bpf_dv34hg_20190512_v01.cdf
#test.files=/home/cdaweb/data/0MASTERS/psp_isois-epihi_l2-het-rates3600_00000000_v01.cdf /data/zdata_1/spdf_archive/public/pub/data/psp/isois/epihi/l2/het_rates1h/2019/psp_isois-epihi_l2-het-rates3600_20190410_v01.cdf
#test.files=/home/cdaweb/data/0MASTERS/psp_swp_spc_l3i_00000000_v01.cdf /data/zdata_1/spdf_archive/public/pub/data/psp/sweap/spc/l3/l3i/2019/psp_swp_spc_l3i_20190515_v01.cdf
#test.files=/home/cdaweb/data/0MASTERS/ibex_h3_ena_lo_r09_park_omap_3yr_00000000_v01.cdf /home/cdaweb/data/ibex/h3/release09/ena_lo_park_omap_3yr/ibex_h3_ena_lo_r09_park_omap_3yr_20081225_v01.cdf
#test.files=rbsp-b_h0_rbspice-multi-string-attr_20130118_v01.cdf
#test.files=-h /home/cdaweb/data/0MASTERS/ac_h2_cris_00000000_v01.cdf /home/cdaweb/data/ace/cris/level_2_cdaweb/cris_h2/1997/ac_h2_cris_19970827_v06.cdf /home/cdaweb/data/0MASTERS/ac_h3_mfi_00000000_v01.cdf /home/cdaweb/data/ace/mag/level_2_cdaweb/mfi_h3/1998/ac_h3_mfi_19980101_v01.cdf
#test.files=/home/cdaweb/data/0MASTERS/de1_6sec_magagms_00000000_v01.cdf /home/cdaweb/data/de/de1/magnetic_fields_maga/6sec_magagms_cdaweb/1991/de1_6sec_magagms_19910218_v01.cdf
#test.files=wi_emfits_e0_3dp_19950101_v01.cdf
#test.files=l0_k0_spa_00000000_v01.cdf
#test.files=mms1_dfg_fast_l1a_20150715_v0.7.0.cdf
#test.files=mms1_dfg_fast_l1a_20150715_v0.7.0.cdf mms1_dfg_fast_l1a_20150715_v0.7.1.cdf mms1_dfg_fast_l1a_20150723_v0.7.1.cdf mms1_dfg_fast_l1a_20150727_v0.7.0.cdf mms1_dfg_fast_l1a_20150727_v0.7.1.cdf mms1_feeps_srvy_l1a_ion-top_20150722000000_v1.1.1.cdf
#test.files=91049_eics_de_96s_v01.cdf de1_6sec_magagms_00000000_v01.cdf rbsp-a-ect_fnl-001_rps-ap003-l3_20120201_v1.2.1.cdf rbsp-a_hf_emfisis-l1_20101230200005_v1.1.2.cdf noaa19_poes-sem_16second_20120429_v01.cdf
#cdf.validation.file=resources/cdfValidation/PrbemCdfValidation.xml
cdf.validation.file=resources/cdfValidation/MmsCdfValidation.xml

pkg-name=${name}-${rev}
src-pkg-name=${name}-src-${rev}
app-name=standalone-${pkg-name}
msi-name=${pkg-name}.msi
dmg-name=${pkg-name}.dmg

file.hash=SHA-256
client.name=spdfjavaClasses
client-jar=${client.name}.jar
help.name=${name}-help
help-jar=${help.name}.jar
build-path=${basedir}/${build}
#
# Directory containing application's help content files
#
help-dir=docs/help

#
# JavaHelp installation directory
#
jh.dir.unix=${user.home}/opt/jh2.0
#
# the following is really only true for Solaris 10
#jh.dir.solaris=${java.home}/../../../packages/javax.help-2.0
#jh.dir.solaris=${user.home}/opt/jh2.0
#jh.dir.macosx=${user.home}/opt/jh2.0
jh.dir.win=C:/j2sdk1.4.2_04/jh2.0


cdf.validation.dir=lib/validation
cdasws.dir=lib/cdasws


#
# Options for different versions of Java
#
#java.src=1.6
#java.target=1.6
#java.src=1.7
#java.target=1.7
java.src=1.8
java.target=1.8
#java.target.bootclasspath=/usr/jdk/instances/jdk1.5.0/jre/lib/rt.jar
#java.target.bootclasspath=/usr/jdk/instances/jdk1.6.0/jre/lib/rt.jar
#java.target.bootclasspath=${user.home}/opt/jdk/jdk1.6.0_45/jre/lib/rt.jar
#java.target.bootclasspath=${user.home}/opt/jdk/jdk1.6.0_45/jre/lib/rt.jar
#java.target.bootclasspath=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/rt.jar
java.target.extdirs=

#
# Since java.ext.dirs is set to nothing on some platforms, define
#
java-ext-dirs=${java.home}/lib/ext

#
# Since Java 9 SE removed JAXB, we need to get it from Java EE
#
#javaee.home=${user.home}/opt/payara/201/payara5/glassfish
#javaee.home=${user.home}/opt/payara/2020.5/payara5/glassfish
javaee.home=${user.home}/opt/payara/5.2022.5/payara5/glassfish
#javaee.home=${user.home}/opt/payara/6.2024.1/payara6/glassfish
javaee.lib=${javaee.home}/lib
javaee.mod=${javaee.home}/modules
#jaxb.dir=${javaee.mod}/endorsed
#jaxb.dir=web/JaxB

build=build
src=src
dist=dist
#
# The following needs to be defined (with no value) so it can be used to
# name the Mac OS 8/9 unique jar.
#
client-version=

#
# CDF library jar
#
cdf-jar-win=C:\Program Files\cdf31dist\lib\cdfjava.jar

#
# For Jar signing
#
#tsa.url=https://timestamp.geotrust.com/tsa
#tsa.url=http://sha256timestamp.ws.symantec.com/sha256/timestamp
tsa.url=http://timestamp.digicert.com/
keystore-solaris=/cdrom/cdrom/ssdoo-keystore
keystore-macosx=/Volumes/CDROM/ssdoo-keystore
keystore-win=d:\ssdoo-keystore

