#
# Note that some of the "program." properties are assigned values by the
# build process.
#
program.name=SKTEditor
program.version=%VERSION*
#program.build.platform=%BUILD_PLATFORM*
#program.build.compiler=%BUILD_COMPILER*
program.build.date=%BUILD_DATE*
# CDFEditor Setup
image.path=images/
custom.icon.path=images/icons/20x20/
icon.path=images/toolbarButtonGraphics/general/
logo.gsfc=gsfc_logo.gif
logo.ssdoo=ssdoosm.gif
logo.spdf=spdf_logo_new.gif
logo.cdf_file=CDF_Logo3.gif
logo.skt_file=sktFile.gif
logo.nonrvskt_file=sktFile.gif
logo.nc_file=ncFile.gif
#####################
### Projects     ####
#####################
gAttr.projects=LWS>Living With a Star:\
STP>Solar-Terrestrial Physics
#########################
### Acknowledgements ####
#########################
gAttr.acknowledgements=\ 
#####################
### Rules of use ####
#####################
gAttr.rulesOfUse=\ 
#########################
### Time Resolutions ####
#########################
gAttr.timeResolutions=\ 
#########################
### Generation Dates ####
#########################
gAttr.generationDates=\ 
#########################
### PI Affiliations  ####
#########################
gAttr.piAffiliations=\ 
#########################
### Data Versions    ####
#########################
gAttr.dataVersions=01:02:03:04:05:06:07:08:09:10:1.0.0:1.0.0-000
#####################
### Disciplines  ####
#####################
gAttr.disciplines= \ :Space Physics>Magnetospheric Science:\
Space Physics>Interplanetary Studies:\
Space Physics>Ionospheric Science:\
Solar Physics>Heliospheric Physics:\
Solar Physics>Ultraviolet Observations
#####################
### Source Names ####
#####################
gAttr.source_names=AC>Advanced Composition Explorer:\
 ACE>Advanced Composition Explorer:\
 Alouette-1>:\
 Alouette-2>:\
 C1>Cluster spacecraft 1:\
 C2>Cluster spacecraft 2:\
 C3>Cluster spacecraft 3:\
 C4>Cluster spacecraft 4:\
 CANOPUS>Canadian Auroral Network Open Program Unified Study:\
 CL>Cluster:\
 CRRES>Combined Radiation Release Effects Spacecraft:\
 DARN>Dual Auroral Radar Network:\
 DMSP>Defense Meteorilogical Satellite Program:\
 EQ>Equator-S:\
 FAST>Fast Auroral SnapshoT:\
 FMI>Finnish Meteorological Institute:\
 Geotail>:\
 GOES10>Geostationary Operational Environmental Satellite 10:\
 GOES11>Geostationary Operational Environmental Satellite 11:\
 GOES12>Geostationary Operational Environmental Satellite 12:\
 GOES6>Geostationary Operational Environmental Satellite 6:\
 GOES7>Geostationary Operational Environmental Satellite 7:\
 GOES8>Geostationary Operational Environmental Satellite 8:\
 GOES9>Geostationary Operational Environmental Satellite 9:\
 Genesis>:\
 Helios-1>:\
 Helios-2>:\
 IMAGE>Imager for Magnetopause to Auroral Global Exploration:\
 IMP7>Interplanetary Monitoring Platform 7:\
 IMP8>Interplanetary Monitoring Platform 8:\
 IBAuroral>Interball Auroral Probe:\
 IBGround>Interball Ground Based Data:\
 IBTail>Interball Tail Probe:\
 LANL1989>Los Alamos National Laboratory 1989_046:\
 LANL1990>Los Alamos National Laboratory 1990_-95:\
 LANL1991>Los Alamos National Laboratory 1989_080:\
 LANL1994>Los Alamos National Laboratory 1994_084:\
 LANL1997>Los Alamos National Laboratory 1997:\
 LANL2001>Los Alamos National Laboratory 2001:\
 LANL2002>Los Alamos National Laboratory 2002:\
 MMS1>MMS Satellite Number 1:\
 MMS2>MMS Satellite Number 2:\
 MMS3>MMS Satellite Number 3:\
 MMS4>MMS Satellite Number 4:\
 MMS>MMS Constellation:\
 NOAA5>National Oceanic and Atmospheric Administration 5:\
 NOAA6>National Oceanic and Atmospheric Administration 6:\
 NOAA7>National Oceanic and Atmospheric Administration 7:\
 NOAA8>National Oceanic and Atmospheric Administration 8:\
 NOAA10>National Oceanic and Atmospheric Administration 10:\
 NOAA12>National Oceanic and Atmospheric Administration 12:\
 NOAA14>National Oceanic and Atmospheric Administration 14:\
 OMNI>Combined 1 Hour Interplantary data At Earth:\
 Polar>Polar Plasma Laboratory:\
 RBSP-A>Radiation Belt Storm Probe A:\
 RBSP-B>Radiation Belt Storm Probe B:\
 SAMPEX>Solar Anomalous Magnetospheric Particle Explorer:\
 SESAME>Satellite Experiments Simultaneous with Antarctic Measurements:\
 SNOE>Student Nitric Oxide Explorer:\
 SOHO>SOlar Heliospheric Observatory:\
 STA>STEREO (Solar TErrestrial RElations Observatory) Ahead:\
 STB>STEREO (Solar TErrestrial RElations Observatory) Behind:\
 TIMED>Thermosphere+Ionosphere+Mesosphere+Energetics and Dynamics:\
 THA>THEMIS (Time History of Events and Macroscale Interactions during Substorms) A:\
 THB>THEMIS (Time History of Events and Macroscale Interactions during Substorms) B:\
 THC>THEMIS (Time History of Events and Macroscale Interactions during Substorms) C:\
 THD>THEMIS (Time History of Events and Macroscale Interactions during Substorms) D:\
 THE>THEMIS (Time History of Events and Macroscale Interactions during Substorms) E:\
 THG>THEMIS (Time History of Events and Macroscale Interactions during Substorms) Ground-Based:\
 TWINS1>Two Wide-angle Imaging Neutral-atom Spectrometers 1:\
 TWINS2>Two Wide-angle Imaging Neutral-atom Spectrometers 2:\
 Ulysses>:\
 Wind>Wind Interplanetary Plasma Laboratory
#####################
###  Data Types  ####
#####################
gAttr.data_types=AT>Attitude:\
AV>Average Ionogram:\
ED>Event Data:\
EJ>Earth Camera Images, processed:\
H0>High Time Resolution:\
H1>Hot Plasma Moments:\
H2>Solar Wind Plasma Distribution Function:\
H3>Hot Plasma Distribution Function:\
K0>Key Parameter:\
K1>Key Parameter:\
M0>10 minute resolution:\
OR>Orbit:\
PA>Platform Attitude:\
SP>Summary Parameter:\
VS>Validated Summary Data
#####################
###  Descriptors ####
#####################
gAttr.descriptors=ECT>Energetic Particle, Composition and Thermal Plasma Suite:\
EFW>Electric Field and Waves:\
EMFISIS>Electric and Magnetic Field Instrument Suite and Integrated Science:\
PSBR>Proton Spectrometer Belt Research:\
RBSPICE>Radiation Belt Storm Probes Ion Composition Experiment 
#########################
### Instrument Types ####
#########################
gAttr.instrumentTypes=Activity Indices:\
Electric Fields (space):\
Engineering:\
Ephemeris:\
Gamma and X-Rays:\
Ground-Based HF Radars:\
Ground-Based Imagers:\
Ground-Based Incoherent-Scatter Radar:\
Ground-Based Magnetometers, Riometers, Sounders:\
Ground-Based VLF/ELF/ULF, Photometrics:\
Housekeeping:\
Imaging and Remote Sensing (ITM/Earth):\
Imaging and Remote Sensing (Magnetosphere/Earth):\
Imaging and Remote Sensing (Sun and Earth):\
Imaging and Remote Sensing (Sun):\
Magnetic Fields (space):\
Particles (space):\
Plasma and Solar Wind:\
Radio and Plasma Waves (space)
#########################
### File Naming Convention ####
#   DELETE THIS AFTER R1.3.1.16 (the code no longer uses it)
#########################
gAttr.file_naming_convention = source_datatype_descriptor:\
source_descriptor_datatype
#########################
###    ADID Refs      ###
#########################
gAttr.adidRefs=NSSD0110
#########################
###  Mission Groups   ###
#########################
gAttr.missionGroups=ACE:\
AMPTE:\
Cluster:\
Dynamics Explorer:\
Equator-S:\
FAST:\
Geosynchronous Investigations:\
Geotail:\
GMS3:\
Ground-Based Investigations:\
Hawkeye:\
IMAGE:\
IMP8:\
Interball:\
Interball Auroral Probe:\
Interball Ground-Based:\
ISEE:\
ISS:\
MMS:\
OMNI:\
Polar:\
RBSP:\
SAMPEX:\
STEREO:\
SCATHA:\
SOHO:\
Ulysses:\
Viking (Sweden):\
Wind
#####################
###  Additional Attributes  ####
#####################
gAttr.standard=Parents:\
Skeleton_version:\
Software_version:\
Validate
vAttr.standard=AVG_TYPE:\
COMPONENT_0:\
DELTA_PLUS_VAR:\
DELTA_MINUS_VAR:\
FUNCTION:\
VIRTUAL:\
DERIVN:\
sig_digits:\
SI_CONVERSION:\
V_PARENT
##########################
###Variable Attributes ###
##########################
avg.types=: :Standard:Angle (degrees):Angle (radians):Angle (hour):RMS:log:decibel:cosine:none

scale.types=: :Linear:Log

#
# the following is no longer used.  See istp.DisplayType.java
#
#display.types=Bar Chart:Flux Image:Flux Movie:Fuv Image:Fuv Movie:Image:\
#Label:Line:List:Map Image:Map Movie:Movie:Orbit: Plasma Movie: \
#Plasmagram:Radar Vector:Site Map:Spectrogram:Stack Plot:\
#Time Series:Time Text:Topside Ionogram:Wind Movie:Wind Plot:XY Plot

key.classes=anisotropy:current:density:electric_field:magnetic_field:\
particle_flux:photon_flux:position:potential:power:pressure:temperature:\
velocity:angle:energy:flag:frequency:label:number:ratio:significance:\
source:species:time:uncertainty:wavelength

variable.types=Data:Support Data:Metadata:Ignore Data

dimensions=0:1:2:3

cdf.datatypes=CDF_BYTE:CDF_INT1:CDF_UINT1:CDF_INT2:CDF_UINT2:CDF_INT4:\
CDF_UINT4:CDF_REAL4:CDF_FLOAT:CDF_REAL8:CDF_DOUBLE:CDF_EPOCH:CDF_EPOCH16:CDF_CHAR:CDF_UCHAR

